import { ESLint } from 'eslint';
import { describe, expect, it } from 'vitest';

const eslint = new ESLint({ cwd: process.cwd() });
const ruleId = 'ghaf/line-comments-only';

async function commentRuleMessages(source: string, filePath = 'comment-rule-probe.ts') {
  const results = await eslint.lintText(source, { filePath });
  const result = results[0];
  if (!result) throw new Error('ESLint returned no result for the comment-rule probe');
  return result.messages.filter((message) => message.ruleId === ruleId);
}

describe('source comment lint rule', () => {
  it('rejects regular block and JSDoc comments', async () => {
    const source = [
      '/* explain the value */',
      'const value = 1;',
      '/** explain the shape */',
      'interface Shape { readonly value: number }',
    ].join('\n');

    await expect(commentRuleMessages(source)).resolves.toHaveLength(2);
  }, 15_000);

  it('accepts consecutive line comments', async () => {
    const source = [
      '// Explain the value.',
      '// Keep this note on a second line.',
      'const value = 1;',
    ].join('\n');

    await expect(commentRuleMessages(source)).resolves.toHaveLength(0);
  });

  it('keeps license headers and build directives that require block syntax', async () => {
    const source = [
      '/*! Project license */',
      '/* Copyright 2026 Example. Licensed under MIT. */',
      "const url = './module';",
      'void import(/* @vite-ignore */ url);',
      'void import(/* webpackMode: "eager" */ url);',
      'void import(/* webpackPrefetch: true */ url);',
      'const value = /* @__PURE__ */ Number(1);',
      '/* c8 ignore next 8 */',
    ].join('\n');

    await expect(commentRuleMessages(source)).resolves.toHaveLength(0);
  });

  it('rejects ordinary comments that imitate preserved license syntax', async () => {
    const source = [
      '/*! ordinary implementation note */',
      '/* Check the license state before loading. */',
      '/* Copyright handling belongs in this function. */',
    ].join('\n');

    await expect(commentRuleMessages(source)).resolves.toHaveLength(3);
  });

  it('does not treat strings, globs, or regular expressions as comments', async () => {
    const source = [
      "const glob = '**/*.ts';",
      "const text = '/* still text */';",
      'const matcher = /\\/\\*|\\*\\//u;',
    ].join('\n');

    await expect(commentRuleMessages(source)).resolves.toHaveLength(0);
  });

  it('ignores the Expo-generated declaration file', async () => {
    await expect(
      commentRuleMessages('/** generated by Expo */\nexport {};', 'expo-env.d.ts'),
    ).resolves.toHaveLength(0);
  });
});
