export const cloudDocumentResources = {
  en: {
    savedOnServer: 'Saved to your family account.',
    loading: 'Loading your family records…',
    unavailable: 'Your records could not be loaded. Refresh to try again.',
    error: 'The change was not confirmed. Your draft is still here.',
    conflict: 'This record changed on another device. Refresh and review before saving again.',
    saving: 'Saving…',
    refresh: 'Refresh',
    retry: 'Retry the same request',
    emptyChildren: 'Add a Child to your family before creating their plans.',
    privateBoundary:
      'Private family records. Study results are self-reported and never earn Seeds.',
    connections: 'Family people',
    preferences: 'Child preferences',
    templates: 'Reusable task wording',
    newTemplate: 'New wording',
    edit: 'Edit',
    remove: 'Delete',
    useTemplate: 'Use this wording',
    titleAr: 'Arabic title',
    titleEn: 'English title',
    actionAr: 'Arabic positive action',
    actionEn: 'English positive action',
    category: 'Category',
    once: 'Once',
    recurrent: 'Recurring',
    noTemplates: 'No saved task wording yet.',
    preferencesEmpty:
      'Choose the preferences you want to save. Nothing is inferred about your Child.',
    preparedSuggestions: 'Prepared suggestions from saved preferences. No AI provider is called.',
    chooseSex: 'Choose an address form',
    male: 'Masculine',
    female: 'Feminine',
    language: 'Preferred language',
    ar: 'Arabic',
    en: 'English',
    both: 'Arabic and English',
    avatar: 'Tree avatar',
    personalizationEnabled: 'Use these preferences for prepared suggestions',
    interests: 'Interests',
    hobbies: 'Hobbies',
    accessibilityDefaults: 'Accessibility',
    supportPreferences: 'Preferred support',
    customInterest: 'Another interest',
    customHobby: 'Another hobby',
    customSupportPreference: 'Another support preference',
    customAccessibility: 'Another accessibility preference',
    options: {
      ghaf_tree: 'Ghaf tree',
      leaf: 'Leaf',
      flower: 'Flower',
      energy_leaf: 'Energy leaf',
      water_drop: 'Water drop',
      nature: 'Nature',
      making: 'Making',
      stories: 'Stories',
      family_helping: 'Helping family',
      sustainability: 'Sustainability',
      drawing: 'Drawing',
      reading: 'Reading',
      sports: 'Sports',
      puzzles: 'Puzzles',
      gardening: 'Gardening',
      larger_text: 'Larger text',
      simpler_instructions: 'Simpler instructions',
      high_contrast: 'High contrast',
      reduced_motion: 'Reduced motion',
      short_steps: 'Short steps',
      visual_examples: 'Visual examples',
      extra_time: 'Extra time',
      adult_alongside: 'Adult alongside',
      quiet_reminders: 'Quiet reminders',
    },
    learningDisabled: 'This learning package is awaiting its content and accessibility review.',
    learningLocked: 'Mangrove Roots becomes available at 132 confirmed Seeds.',
    learningSaved: 'Your learning completion is saved. This activity adds no Seeds or tree growth.',
    learningStart: 'Start this learning route',
    learningStep: 'I have read or listened to this section',
    learningComplete: 'Complete learning',
    story: 'Story',
    accessible: 'Accessible text',
    learningRetry: 'Try another answer; your progress is kept.',
  },
  ar: {
    savedOnServer: 'تم الحفظ في حساب أسرتك.',
    loading: 'جارٍ تحميل سجلات أسرتك…',
    unavailable: 'تعذّر تحميل سجلاتك. حدّث الصفحة للمحاولة مجددًا.',
    error: 'لم يتم تأكيد التغيير. ما زالت مسودتك هنا.',
    conflict: 'تغيّر هذا السجل على جهاز آخر. حدّثه وراجعه قبل الحفظ مجددًا.',
    saving: 'جارٍ الحفظ…',
    refresh: 'تحديث',
    retry: 'إعادة محاولة الطلب نفسه',
    emptyChildren: 'أضف طفلًا إلى أسرتك قبل إنشاء خططه.',
    privateBoundary: 'سجلات خاصة بالأسرة. نتائج الدراسة يذكرها الطفل بنفسه ولا تمنح بذورًا.',
    connections: 'أفراد الأسرة',
    preferences: 'تفضيلات الطفل',
    templates: 'صياغات مهام قابلة لإعادة الاستخدام',
    newTemplate: 'صياغة جديدة',
    edit: 'تعديل',
    remove: 'حذف',
    useTemplate: 'استخدام هذه الصياغة',
    titleAr: 'العنوان بالعربية',
    titleEn: 'العنوان بالإنجليزية',
    actionAr: 'الفعل الإيجابي بالعربية',
    actionEn: 'الفعل الإيجابي بالإنجليزية',
    category: 'الفئة',
    once: 'مرة واحدة',
    recurrent: 'متكررة',
    noTemplates: 'لا توجد صياغات مهام محفوظة بعد.',
    preferencesEmpty: 'اختر التفضيلات التي تريد حفظها. لا نستنتج أي صفات عن طفلك.',
    preparedSuggestions:
      'اقتراحات مُعدّة مسبقًا من التفضيلات المحفوظة. لا يتم استدعاء مزوّد ذكاء اصطناعي.',
    chooseSex: 'اختر صيغة المخاطبة',
    male: 'المذكر',
    female: 'المؤنث',
    language: 'اللغة المفضّلة',
    ar: 'العربية',
    en: 'الإنجليزية',
    both: 'العربية والإنجليزية',
    avatar: 'رمز الشجرة',
    personalizationEnabled: 'استخدام هذه التفضيلات للاقتراحات المُعدّة مسبقًا',
    interests: 'الاهتمامات',
    hobbies: 'الهوايات',
    accessibilityDefaults: 'إمكانية الوصول',
    supportPreferences: 'المساعدة المفضّلة',
    customInterest: 'اهتمام آخر',
    customHobby: 'هواية أخرى',
    customSupportPreference: 'تفضيل آخر للمساعدة',
    customAccessibility: 'تفضيل آخر لإمكانية الوصول',
    options: {
      ghaf_tree: 'شجرة غاف',
      leaf: 'ورقة',
      flower: 'زهرة',
      energy_leaf: 'ورقة طاقة',
      water_drop: 'قطرة ماء',
      nature: 'الطبيعة',
      making: 'الصنع',
      stories: 'القصص',
      family_helping: 'مساعدة الأسرة',
      sustainability: 'الاستدامة',
      drawing: 'الرسم',
      reading: 'القراءة',
      sports: 'الرياضة',
      puzzles: 'الألغاز',
      gardening: 'الزراعة',
      larger_text: 'نص أكبر',
      simpler_instructions: 'تعليمات أبسط',
      high_contrast: 'تباين عالٍ',
      reduced_motion: 'حركة أقل',
      short_steps: 'خطوات قصيرة',
      visual_examples: 'أمثلة مرئية',
      extra_time: 'وقت إضافي',
      adult_alongside: 'وجود شخص بالغ',
      quiet_reminders: 'تذكيرات هادئة',
    },
    learningDisabled: 'حزمة التعلّم هذه تنتظر مراجعة المحتوى وإمكانية الوصول.',
    learningLocked: 'يتاح تعلّم جذور القرم عند الوصول إلى ١٣٢ بذرة مؤكدة.',
    learningSaved: 'تم حفظ إكمال التعلّم. لا يضيف هذا النشاط بذورًا أو نموًا للشجرة.',
    learningStart: 'بدء مسار التعلّم',
    learningStep: 'قرأت هذا الجزء أو استمعت إليه',
    learningComplete: 'إكمال التعلّم',
    story: 'قصة',
    accessible: 'نص ميسّر',
    learningRetry: 'جرّب إجابة أخرى؛ يبقى تقدّمك محفوظًا.',
  },
};
