export const colors = {
  surface: '#F9FAF5',
  surfaceDim: '#D9DAD6',
  surfaceBright: '#F9FAF5',
  surfaceContainerLowest: '#FFFFFF',
  surfaceContainerLow: '#F3F4EF',
  surfaceContainer: '#EDEEE9',
  surfaceContainerHigh: '#E7E9E4',
  surfaceContainerHighest: '#E2E3DE',
  onSurface: '#1A1C19',
  onSurfaceVariant: '#3F4944',
  inverseSurface: '#2E312E',
  inverseOnSurface: '#F0F1EC',
  outline: '#6F7973',
  outlineVariant: '#BEC9C2',
  surfaceTint: '#146B51',
  primary: '#00503B',
  onPrimary: '#FFFFFF',
  primaryContainer: '#126A50',
  onPrimaryContainer: '#98E7C6',
  inversePrimary: '#87D6B6',
  primaryFixed: '#A3F3D1',
  primaryFixedDim: '#87D6B6',
  onPrimaryFixed: '#002116',
  onPrimaryFixedVariant: '#00513C',
  secondary: '#006A64',
  onSecondary: '#FFFFFF',
  secondaryContainer: '#8EF1E7',
  onSecondaryContainer: '#006F68',
  secondaryFixed: '#91F3E9',
  secondaryFixedDim: '#74D7CD',
  onSecondaryFixed: '#00201E',
  onSecondaryFixedVariant: '#00504B',
  tertiary: '#5E4100',
  onTertiary: '#FFFFFF',
  tertiaryContainer: '#7C5700',
  onTertiaryContainer: '#FFD182',
  tertiaryFixed: '#FFDEAA',
  tertiaryFixedDim: '#F7BD4F',
  onTertiaryFixed: '#271900',
  onTertiaryFixedVariant: '#5F4100',
  error: '#BA1A1A',
  onError: '#FFFFFF',
  errorContainer: '#FFDAD6',
  onErrorContainer: '#93000A',
  ghafEmerald: '#126A50',
  deepForest: '#0D3128',
  mangroveTeal: '#188B83',
  solarAmber: '#F2B84B',
  pearlGround: '#F7F8F3',
  ink: '#14221D',
  white: '#FFFFFF',
  transparent: 'transparent',

  // Compatibility aliases for the preserved Revision 1 surfaces.
  ghaf: '#126A50',
  ghafPressed: '#00503B',
  forest: '#0D3128',
  forestSoft: '#3F4944',
  leaf: '#87D6B6',
  leafLight: '#DDECE5',
  leafMist: '#EFF5F1',
  mangrove: '#188B83',
  water: '#74D7CD',
  waterLight: '#E0F4F1',
  sand: '#D8C28F',
  sandLight: '#F1E9D7',
  ivory: '#F7F8F3',
  earth: '#6A503C',
  gold: '#C78B28',
  goldLight: '#FFDEAA',
  goldGlow: '#FFF4DF',
  sky: '#DCEAE5',
  inkMuted: '#58645E',
  line: '#D7DDD9',
  success: '#126A50',
  successLight: '#DDECE5',
  danger: '#BA1A1A',
  dangerLight: '#FFDAD6',
  coral: '#BA1A1A',
  coralLight: '#FFDAD6',
} as const;

export const spacing = {
  xxs: 4,
  xs: 8,
  sm: 12,
  md: 16,
  lg: 20,
  xl: 24,
  xxl: 32,
  xxxl: 40,
  huge: 56,
  massive: 64,
} as const;

export const radii = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 24,
  sheet: 28,
  pill: 999,
} as const;

export const fontFamilies = {
  alexandriaRegular: 'Alexandria_400Regular',
  alexandriaBold: 'Alexandria_700Bold',
  alexandriaExtraBold: 'Alexandria_800ExtraBold',
  readexRegular: 'ReadexPro_400Regular',
  readexMedium: 'ReadexPro_500Medium',
  readexSemiBold: 'ReadexPro_600SemiBold',
  readexBold: 'ReadexPro_700Bold',
} as const;

export const typography = {
  family: fontFamilies.readexRegular,
  families: fontFamilies,
  sizes: {
    caption: 14,
    label: 14,
    compactBody: 16,
    control: 16,
    body: 17,
    bodyLarge: 18,
    heading: 24,
    title: 30,
    hero: 32,
    wordmark: 36,
    display: 48,
  },
  lineHeights: {
    caption: 22,
    label: 22,
    compactBody: 26,
    control: 24,
    body: 28,
    bodyLarge: 30,
    heading: 34,
    title: 42,
    hero: 42,
    wordmark: 44,
    display: 58,
  },
  weights: {
    regular: '400',
    medium: '500',
    semibold: '600',
    bold: '700',
    heavy: '800',
  },
  roles: {
    display: {
      fontFamily: fontFamilies.alexandriaExtraBold,
      fontSize: 48,
      lineHeight: 58,
    },
    wordmark: {
      fontFamily: fontFamilies.alexandriaExtraBold,
      fontSize: 36,
      lineHeight: 44,
    },
    hero: {
      fontFamily: fontFamilies.alexandriaBold,
      fontSize: 32,
      lineHeight: 42,
    },
    parentHero: {
      fontFamily: fontFamilies.alexandriaBold,
      fontSize: 30,
      lineHeight: 42,
    },
    screenTitle: {
      fontFamily: fontFamilies.alexandriaBold,
      fontSize: 24,
      lineHeight: 36,
    },
    bodyLarge: {
      fontFamily: fontFamilies.readexRegular,
      fontSize: 18,
      lineHeight: 30,
    },
    body: {
      fontFamily: fontFamilies.readexRegular,
      fontSize: 17,
      lineHeight: 28,
    },
    compactBody: {
      fontFamily: fontFamilies.readexRegular,
      fontSize: 16,
      lineHeight: 26,
    },
    control: {
      fontFamily: fontFamilies.readexSemiBold,
      fontSize: 16,
      lineHeight: 24,
    },
    label: {
      fontFamily: fontFamilies.readexSemiBold,
      fontSize: 14,
      lineHeight: 22,
    },
    caption: {
      fontFamily: fontFamilies.readexRegular,
      fontSize: 14,
      lineHeight: 22,
    },
  },
} as const;

export const shadows = {
  soft: {
    boxShadow: '0 2px 10px rgba(20, 34, 29, 0.06)',
  },
  lifted: {
    boxShadow: '0 16px 40px rgba(20, 34, 29, 0.12)',
  },
  sheet: {
    boxShadow: '0 -8px 30px rgba(20, 34, 29, 0.08)',
  },
} as const;

export const motion = {
  duration: {
    quick: 120,
    standard: 220,
    slow: 320,
    reveal: 420,
    growth: 650,
  },
  easing: [0.2, 0.8, 0.2, 1] as const,
} as const;

export const layout = {
  maxContentWidth: 720,
  accessContentWidth: 600,
  compactContentWidth: 520,
  readableContentWidth: 440,
  touchTarget: 48,
  controlHeight: 56,
  screenPadding: 20,
  desktopPadding: 64,
} as const;

export const opacity = {
  disabled: 0.48,
  pressed: 0.78,
  subtle: 0.62,
  scrim: 0.46,
} as const;

export const tokens = {
  colors,
  fontFamilies,
  layout,
  motion,
  opacity,
  radii,
  shadows,
  spacing,
  typography,
} as const;

export type AppColor = keyof typeof colors;
